language: c

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.net#em.slashem.me"
#    skip_join: true
#    on_success: always
#    on_failure: always
#    template:
#      - "%{commit_subject} (%{result} %{branch} #%{build_number}) %{build_url} Diff: %{compare_url}"

matrix:
  include:
    # linux/clang
    - name: linux/clang/dlblib
      os: linux
      dist: focal
      compiler: clang
      before_install:
        - sudo apt install libncursesw5-dev
      script:
        - make DLBMODE=lib install
    - name: linux/clang/dlbembed
      os: linux
      dist: focal
      compiler: clang
      before_install:
        - sudo apt install libncursesw5-dev
      script:
        - make DLBMODE=embed install
    - name: linux/clang/flat
      os: linux
      dist: focal
      compiler: clang
      before_install:
        - sudo apt install libncursesw5-dev
      script:
        - make DLBMODE=none install

    # linux/gcc
    - name: linux/gcc/dlblib
      os: linux
      dist: focal
      compiler: gcc
      before_install:
        - sudo apt install libncursesw5-dev
      script:
        - make DLBMODE=lib install
    - name: linux/gcc/dlbembed
      os: linux
      dist: focal
      compiler: gcc
      before_install:
        - sudo apt install libncursesw5-dev
      script:
        - make DLBMODE=embed install
    - name: linux/gcc/flat
      os: linux
      dist: focal
      compiler: gcc
      before_install:
        - sudo apt install libncursesw5-dev
      script:
        - make DLBMODE=none install

    # linux/tcc
    - name: linux/tcc/dlblib
      os: linux
      dist: focal
      compiler: tcc
      before_install:
        - sudo apt update
        - sudo apt install libncursesw5-dev tcc
      script:
        - make DLBMODE=lib install CC=tcc
    - name: linux/tcc/dlbembed
      os: linux
      dist: focal
      compiler: tcc
      before_install:
        - sudo apt update
        - sudo apt install libncursesw5-dev tcc
      script:
        - make DLBMODE=embed install CC=tcc
    - name: linux/tcc/flat
      os: linux
      dist: focal
      compiler: tcc
      before_install:
        - sudo apt update
        - sudo apt install libncursesw5-dev tcc
      script:
        - make DLBMODE=none install CC=tcc

    # macos/clang
    - name: macos/clang/dlblib
      os: osx
      osx_image: xcode10.2
      compiler: clang
      script:
        - make DLBMODE=lib install
    - name: macos/clang/dlbembed
      os: osx
      osx_image: xcode10.2
      compiler: clang
      script:
        - make DLBMODE=embed install
    - name: macos/clang/flat
      os: osx
      osx_image: xcode10.2
      compiler: clang
      script:
        - make DLBMODE=none install
